# Generated by Django 2.1.5 on 2019-01-22 10:50

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категори', 'verbose_name_plural': 'Категори'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Бүтээгдэхүүн', 'verbose_name_plural': 'Бүтээгдэхүүнүүд'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Бүтээгдэхүүний зураг', 'verbose_name_plural': 'Бүтээгдэхүүний зураг'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайд'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Дэд категори', 'verbose_name_plural': 'Дэд категори'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.AddField(
            model_name='product',
            name='special',
            field=models.BooleanField(default=False, verbose_name='Онцгой бүтээгдэхүүн'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main_app.SubCategory', verbose_name='Категори'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Үнэ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(upload_to='thumbnails/', verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Гарчиг'),
        ),
    ]
