# Generated by Django 2.1.5 on 2019-01-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190124_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='maromere',
            field=models.BooleanField(default=False),
        ),
    ]
